// <auto-generated />
using System;
using AGROCHEM.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AGROCHEM.Migrations
{
    [DbContext(typeof(AgrochemContext))]
    partial class AgrochemContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AGROCHEM.Models.Entities.ChemicalAgent", b =>
                {
                    b.Property<int>("ChemAgentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ChemAgentId"));

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("ChemAgentId")
                        .HasName("PK__Chemical__C41C86D6938BE878");

                    b.ToTable("ChemicalAgent", "agro_chem");
                });

            modelBuilder.Entity("AGROCHEM.Models.Entities.ChemicalTreatment", b =>
                {
                    b.Property<int>("ChemTreatId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ChemTreatId"));

                    b.Property<decimal?>("Area")
                        .HasColumnType("decimal(6, 2)");

                    b.Property<int?>("ChemAgentId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("Date")
                        .HasColumnType("datetime");

                    b.Property<decimal?>("Dose")
                        .HasColumnType("decimal(6, 2)");

                    b.Property<int?>("PlantId")
                        .HasColumnType("int");

                    b.Property<int?>("PlotId")
                        .HasColumnType("int");

                    b.Property<string>("Reason")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("ChemTreatId")
                        .HasName("PK__Chemical__2CFBF0BF3FA16EB3");

                    b.HasIndex("ChemAgentId");

                    b.HasIndex("PlantId");

                    b.HasIndex("PlotId");

                    b.ToTable("ChemicalTreatment", "agro_chem");
                });

            modelBuilder.Entity("AGROCHEM.Models.Entities.ChemicalUse", b =>
                {
                    b.Property<int>("ChemUseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ChemUseId"));

                    b.Property<int?>("ChemAgentId")
                        .HasColumnType("int");

                    b.Property<int?>("MaxDays")
                        .HasColumnType("int");

                    b.Property<decimal?>("MaxDose")
                        .HasColumnType("decimal(3, 1)");

                    b.Property<int?>("MaxWater")
                        .HasColumnType("int");

                    b.Property<int?>("MinDays")
                        .HasColumnType("int");

                    b.Property<decimal?>("MinDose")
                        .HasColumnType("decimal(3, 1)");

                    b.Property<int?>("MinWater")
                        .HasColumnType("int");

                    b.Property<int?>("PlantId")
                        .HasColumnType("int");

                    b.HasKey("ChemUseId")
                        .HasName("PK__Chemical__8DFE527D2FA71BBD");

                    b.HasIndex("ChemAgentId");

                    b.HasIndex("PlantId");

                    b.ToTable("ChemicalUse", "agro_chem");
                });

            modelBuilder.Entity("AGROCHEM.Models.Entities.Cultivation", b =>
                {
                    b.Property<int>("CultivationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CultivationId"));

                    b.Property<bool?>("Archival")
                        .HasColumnType("bit");

                    b.Property<decimal?>("Area")
                        .HasColumnType("decimal(6, 2)");

                    b.Property<DateTime?>("HarvestDate")
                        .HasColumnType("datetime");

                    b.Property<int?>("PlantId")
                        .HasColumnType("int");

                    b.Property<int?>("PlotId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("SowingDate")
                        .HasColumnType("datetime");

                    b.HasKey("CultivationId")
                        .HasName("PK__Cultivat__6B84BC3861D273F2");

                    b.HasIndex("PlantId");

                    b.HasIndex("PlotId");

                    b.ToTable("Cultivation", "agro_chem");
                });

            modelBuilder.Entity("AGROCHEM.Models.Entities.Disease", b =>
                {
                    b.Property<int>("DiseaseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DiseaseId"));

                    b.Property<string>("Characteristic")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("PhotoId")
                        .HasColumnType("int");

                    b.Property<string>("Reasons")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DiseaseId")
                        .HasName("PK__Disease__69B53389FD793224");

                    b.HasIndex("PhotoId");

                    b.ToTable("Disease", "agro_chem");
                });

            modelBuilder.Entity("AGROCHEM.Models.Entities.Photo", b =>
                {
                    b.Property<int>("PhotoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PhotoId"));

                    b.Property<byte[]>("BinaryData")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("Extension")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Name")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Type")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("PhotoId")
                        .HasName("PK__Photo__21B7B5E28BA83CA6");

                    b.ToTable("Photo", "agro_chem");
                });

            modelBuilder.Entity("AGROCHEM.Models.Entities.Plant", b =>
                {
                    b.Property<int>("PlantId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PlantId"));

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<int?>("RotationPeriod")
                        .HasColumnType("int");

                    b.HasKey("PlantId")
                        .HasName("PK__Plant__98FE395C7612A201");

                    b.ToTable("Plant", "agro_chem");
                });

            modelBuilder.Entity("AGROCHEM.Models.Entities.PlantDisease", b =>
                {
                    b.Property<int>("PlDiseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PlDiseId"));

                    b.Property<int?>("DiseaseId")
                        .HasColumnType("int");

                    b.Property<int?>("PlantId")
                        .HasColumnType("int");

                    b.HasKey("PlDiseId")
                        .HasName("PK__PlantDis__80ADE8145F484A49");

                    b.HasIndex("DiseaseId");

                    b.HasIndex("PlantId");

                    b.ToTable("PlantDisease", "agro_chem");
                });

            modelBuilder.Entity("AGROCHEM.Models.Entities.Plot", b =>
                {
                    b.Property<int>("PlotId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PlotId"));

                    b.Property<int?>("AddressId")
                        .HasColumnType("int");

                    b.Property<bool?>("Archival")
                        .HasColumnType("bit");

                    b.Property<decimal?>("Area")
                        .HasColumnType("decimal(6, 2)");

                    b.Property<int?>("OwnerId")
                        .HasColumnType("int");

                    b.Property<string>("PlotNumber")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("PlotId")
                        .HasName("PK__Plot__78FA3AA32768209A");

                    b.HasIndex("AddressId");

                    b.HasIndex("OwnerId");

                    b.ToTable("Plot", "agro_chem");
                });

            modelBuilder.Entity("AGROCHEM.Models.Entities.PlotAddress", b =>
                {
                    b.Property<int>("PlotAddressId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PlotAddressId"));

                    b.Property<string>("District")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Location")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Voivodeship")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("PlotAddressId")
                        .HasName("PK__PlotAddr__86A9D57858299DE1");

                    b.ToTable("PlotAddress", "agro_chem");
                });

            modelBuilder.Entity("AGROCHEM.Models.Entities.Role", b =>
                {
                    b.Property<int>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RoleId"));

                    b.Property<string>("Name")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("RoleId")
                        .HasName("PK__Role__8AFACE1A3D14BC7A");

                    b.ToTable("Role", "agro_chem");
                });

            modelBuilder.Entity("AGROCHEM.Models.Entities.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("FirstName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("LastName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Password")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<int?>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("UserId")
                        .HasName("PK__User__1788CC4CEA0B52A2");

                    b.HasIndex("RoleId");

                    b.ToTable("User", "agro_chem");
                });

            modelBuilder.Entity("AGROCHEM.Models.Entities.ChemicalTreatment", b =>
                {
                    b.HasOne("AGROCHEM.Models.Entities.ChemicalAgent", "ChemAgent")
                        .WithMany("ChemicalTreatments")
                        .HasForeignKey("ChemAgentId")
                        .HasConstraintName("FK__ChemicalT__ChemA__3C34F16F");

                    b.HasOne("AGROCHEM.Models.Entities.Plant", "Plant")
                        .WithMany("ChemicalTreatments")
                        .HasForeignKey("PlantId")
                        .HasConstraintName("FK__ChemicalT__Plant__3B40CD36");

                    b.HasOne("AGROCHEM.Models.Entities.Plot", "Plot")
                        .WithMany("ChemicalTreatments")
                        .HasForeignKey("PlotId")
                        .HasConstraintName("FK__ChemicalT__PlotI__3A4CA8FD");

                    b.Navigation("ChemAgent");

                    b.Navigation("Plant");

                    b.Navigation("Plot");
                });

            modelBuilder.Entity("AGROCHEM.Models.Entities.ChemicalUse", b =>
                {
                    b.HasOne("AGROCHEM.Models.Entities.ChemicalAgent", "ChemAgent")
                        .WithMany("ChemicalUses")
                        .HasForeignKey("ChemAgentId")
                        .HasConstraintName("FK__ChemicalU__ChemA__37703C52");

                    b.HasOne("AGROCHEM.Models.Entities.Plant", "Plant")
                        .WithMany("ChemicalUses")
                        .HasForeignKey("PlantId")
                        .HasConstraintName("FK__ChemicalU__Plant__367C1819");

                    b.Navigation("ChemAgent");

                    b.Navigation("Plant");
                });

            modelBuilder.Entity("AGROCHEM.Models.Entities.Cultivation", b =>
                {
                    b.HasOne("AGROCHEM.Models.Entities.Plant", "Plant")
                        .WithMany("Cultivations")
                        .HasForeignKey("PlantId")
                        .HasConstraintName("FK__Cultivati__Plant__339FAB6E");

                    b.HasOne("AGROCHEM.Models.Entities.Plot", "Plot")
                        .WithMany("Cultivations")
                        .HasForeignKey("PlotId")
                        .HasConstraintName("FK__Cultivati__PlotI__32AB8735");

                    b.Navigation("Plant");

                    b.Navigation("Plot");
                });

            modelBuilder.Entity("AGROCHEM.Models.Entities.Disease", b =>
                {
                    b.HasOne("AGROCHEM.Models.Entities.Photo", "Photo")
                        .WithMany("Diseases")
                        .HasForeignKey("PhotoId")
                        .HasConstraintName("FK__Disease__PhotoId__282DF8C2");

                    b.Navigation("Photo");
                });

            modelBuilder.Entity("AGROCHEM.Models.Entities.PlantDisease", b =>
                {
                    b.HasOne("AGROCHEM.Models.Entities.Disease", "Disease")
                        .WithMany("PlantDiseases")
                        .HasForeignKey("DiseaseId")
                        .HasConstraintName("FK__PlantDise__Disea__2EDAF651");

                    b.HasOne("AGROCHEM.Models.Entities.Plant", "Plant")
                        .WithMany("PlantDiseases")
                        .HasForeignKey("PlantId")
                        .HasConstraintName("FK__PlantDise__Plant__2FCF1A8A");

                    b.Navigation("Disease");

                    b.Navigation("Plant");
                });

            modelBuilder.Entity("AGROCHEM.Models.Entities.Plot", b =>
                {
                    b.HasOne("AGROCHEM.Models.Entities.PlotAddress", "Address")
                        .WithMany("Plots")
                        .HasForeignKey("AddressId")
                        .HasConstraintName("FK__Plot__AddressId__1DB06A4F");

                    b.HasOne("AGROCHEM.Models.Entities.User", "Owner")
                        .WithMany("Plots")
                        .HasForeignKey("OwnerId")
                        .HasConstraintName("FK__Plot__OwnerId__1CBC4616");

                    b.Navigation("Address");

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("AGROCHEM.Models.Entities.User", b =>
                {
                    b.HasOne("AGROCHEM.Models.Entities.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .HasConstraintName("FK__User__RoleId__17F790F9");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("AGROCHEM.Models.Entities.ChemicalAgent", b =>
                {
                    b.Navigation("ChemicalTreatments");

                    b.Navigation("ChemicalUses");
                });

            modelBuilder.Entity("AGROCHEM.Models.Entities.Disease", b =>
                {
                    b.Navigation("PlantDiseases");
                });

            modelBuilder.Entity("AGROCHEM.Models.Entities.Photo", b =>
                {
                    b.Navigation("Diseases");
                });

            modelBuilder.Entity("AGROCHEM.Models.Entities.Plant", b =>
                {
                    b.Navigation("ChemicalTreatments");

                    b.Navigation("ChemicalUses");

                    b.Navigation("Cultivations");

                    b.Navigation("PlantDiseases");
                });

            modelBuilder.Entity("AGROCHEM.Models.Entities.Plot", b =>
                {
                    b.Navigation("ChemicalTreatments");

                    b.Navigation("Cultivations");
                });

            modelBuilder.Entity("AGROCHEM.Models.Entities.PlotAddress", b =>
                {
                    b.Navigation("Plots");
                });

            modelBuilder.Entity("AGROCHEM.Models.Entities.Role", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("AGROCHEM.Models.Entities.User", b =>
                {
                    b.Navigation("Plots");
                });
#pragma warning restore 612, 618
        }
    }
}
